export const themes = [
	{
		name: 'Becca',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (1).jpg',
	},
	{
		name: 'Hawat',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (1).png',
	},
	{
		name: 'Otaru',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (2).jpg',
	},
	{
		name: 'Deon',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (2).png',
	},
	{
		name: 'Cyberdom',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (3).png',
	},
	{
		name: 'Join Up',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (4).png',
	},
	{
		name: 'TechLink',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (5).png',
	},
	{
		name: 'WebOn',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (6).png',
	},
	{
		name: 'CleverSoft',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (7).png',
	},
	{
		name: 'BitPal',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (8).png',
	},
	{
		name: 'Foton',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (9).png',
	},
	{
		name: 'Sceon',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (10).png',
	},
	{
		name: 'Synergia',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (11).png',
	},
	{
		name: 'Sparks',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (12).png',
	},
	{
		name: 'Fluid',
		category: 'Technology',
		price: '$85',
		url: '/assets/aside/00_preview.__large_preview (13).png',
	},
];
